version: '3.3'

services:
  db:
    labels:
      wp-dploy: "true"
    image: mysql:5.7
    volumes:
      - ./env/data/mysql:/var/lib/mysql:delegated
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    labels:
      wp-dploy: "true"
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./:/var/www/html:delegated
      - ./env/data/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
  wpcli:
    labels:
      wp-dploy: "true"
    image: wordpress:cli
    user: xfs
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - db
      - wordpress
    links:
      - db:mysql
  dnsmasq:
    labels:
      wp-dploy: "true"
    restart: always
    image: strm/dnsmasq
    command: --log-facility=-
    volumes:
        - ./env/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
        - "53:53/udp"
    cap_add:
        - NET_ADMIN
